@startuml

title __APP's Class Diagram__\n

  package com.avansprojects.antl {
    class AntlApp {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.database {
      abstract class AntlDatabase {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.database {
      class AntlDatabase_Impl {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.retrofit {
      class AntlRetrofit {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.listeners {
      interface AsyncTaskListener {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class Authentication {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      enum Availability {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class AvailabilityConverter {
      }
    }
  }
  

  package com.avansprojects.antl {
    class BR {
    }
  }
  

  package androidx.databinding {
    package androidx.databinding.library {
      package androidx.databinding.library.baseAdapters {
        class BR {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class BottomOffsetDecoration {
      }
    }
  }
  

  package com.avansprojects.antl {
    class BuildConfig {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class CalendarHelper {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.repositories {
      class ContactRepository {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventDateFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventDescriptionFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventImageFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventNameFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class CreateEventViewModel {
      }
    }
  }
  

  package androidx.databinding {
    class DataBinderMapperImpl {
    }
  }
  

  package com.avansprojects.antl {
    class DataBinderMapperImpl {
    }
  }
  

  package androidx.databinding {
    interface DataBindingComponent {
    }
  }
  

  package android.databinding.layouts {
    class DataBindingInfo {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class DateConverter {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class DatePickerFactory {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.listeners {
      interface DatePickerListener {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class Event {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      interface EventDao {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      class EventDao_Impl {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class EventDate {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.createEvent {
      class EventDateAdapter {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      interface EventDateDao {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      class EventDateDao_Impl {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.repositories {
      class EventDateRepository {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.eventOverview {
      class EventOverviewAdapter {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.eventOverview {
      class EventOverviewFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.eventOverview {
      class EventOverviewFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.eventOverview {
      class EventOverviewViewModel {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.repositories {
      class EventRepository {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class Friend {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendAddMenu {
      class FriendAddFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendAddMenu {
      class FriendAddFragmentArgs {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendAddMenu {
      class FriendAddFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendAddMenu {
      class FriendAddViewModel {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendOverview {
      class FriendCardViewHolder {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      interface FriendDao {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      class FriendDao_Impl {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.dto {
        class FriendDto {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendOverview {
      class FriendOverviewAdapter {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendOverview {
      class FriendOverviewFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendOverview {
      class FriendOverviewFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.friendOverview {
      class FriendOverviewViewModel {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.dto {
        class FriendRequestDto {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.services {
        interface FriendService {
        }
      }
    }
  }
  

  package com.bumptech.glide {
    class GeneratedAppGlideModuleImpl {
    }
  }
  

  package com.bumptech.glide {
    class GeneratedRequestManagerFactory {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class GlideApp {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class GlideOptions {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class GlideRequest {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class GlideRequests {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class Group {
      }
    }
  }
  

  package com.avansprojects.antl {
    class LoginFragment {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class LoginFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class LoginFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.dto {
        class LoginRequestDTO {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.services {
        interface LoginService {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class LoginViewModel {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class MyAppGlideModule {
      }
    }
  }
  

  package com.avansprojects.antl {
    class NavGraphDirections {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.helpers {
      class NonSwipeableViewPager {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.retrofit {
      abstract class OkHttpProvider {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.profile {
      class ProfileViewModel {
      }
    }
  }
  

  package androidx.interpolator {
    class R {
    }
  }
  

  package com.google.android.material {
    class R {
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.viewmodel {
      class R {
      }
    }
  }
  

  package com.removeme {
    class R {
    }
  }
  

  package androidx.legacy.coreutils {
    class R {
    }
  }
  

  package androidx.lifecycle {
    class R {
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.service {
      class R {
      }
    }
  }
  

  package com.jakewharton.espresso.okhttp3 {
    class R {
    }
  }
  

  package androidx.slidingpanelayout {
    class R {
    }
  }
  

  package androidx.customview {
    class R {
    }
  }
  

  package androidx.print {
    class R {
    }
  }
  

  package androidx.fragment {
    class R {
    }
  }
  

  package androidx.databinding {
    package androidx.databinding.library {
      package androidx.databinding.library.baseAdapters {
        class R {
        }
      }
    }
  }
  

  package androidx.vectordrawable {
    class R {
    }
  }
  

  package com.bumptech.glide {
    package com.bumptech.glide.gifdecoder {
      class R {
      }
    }
  }
  

  package androidx.transition {
    class R {
    }
  }
  

  package com.avansprojects.antl {
    class R {
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.process {
      class R {
      }
    }
  }
  

  package androidx.appcompat {
    class R {
    }
  }
  

  package androidx.documentfile {
    class R {
    }
  }
  

  package androidx.legacy.v4 {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.ui {
      class R {
      }
    }
  }
  

  package androidx.sqlite.db {
    class R {
    }
  }
  

  package androidx.drawerlayout {
    class R {
    }
  }
  

  package com.auth0.android.jwt {
    class R {
    }
  }
  

  package androidx.recyclerview {
    class R {
    }
  }
  

  package androidx.sqlite.db {
    package androidx.sqlite.db.framework {
      class R {
      }
    }
  }
  

  package androidx.recyclerview {
    package androidx.recyclerview.selection {
      class R {
      }
    }
  }
  

  package androidx.cursoradapter {
    class R {
    }
  }
  

  package androidx.work {
    class R {
    }
  }
  

  package androidx.coordinatorlayout {
    class R {
    }
  }
  

  package androidx.localbroadcastmanager {
    class R {
    }
  }
  

  package androidx.core {
    class R {
    }
  }
  

  package androidx.swiperefreshlayout {
    class R {
    }
  }
  

  package androidx.viewpager {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.common {
      class R {
      }
    }
  }
  

  package androidx.media {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.fragment {
      class R {
      }
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.extensions {
      class R {
      }
    }
  }
  

  package androidx.cardview {
    class R {
    }
  }
  

  package androidx.versionedparcelable {
    class R {
    }
  }
  

  package androidx.databinding {
    package androidx.databinding.library {
      class R {
      }
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.livedata {
      class R {
      }
    }
  }
  

  package androidx.arch.core {
    class R {
    }
  }
  

  package androidx.lifecycle {
    package androidx.lifecycle.livedata {
      package androidx.lifecycle.livedata.core {
        class R {
        }
      }
    }
  }
  

  package android_libs.ub_uiautomator {
    class R {
    }
  }
  

  package androidx.room {
    class R {
    }
  }
  

  package androidx.legacy.coreui {
    class R {
    }
  }
  

  package androidx.navigation {
    class R {
    }
  }
  

  package androidx.loader {
    class R {
    }
  }
  

  package com.bumptech.glide {
    class R {
    }
  }
  

  package androidx.constraintlayout.widget {
    class R {
    }
  }
  

  package androidx.asynclayoutinflater {
    class R {
    }
  }
  

  package com.wdullaer.materialdatetimepicker {
    class R {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class RegisterFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class RegisterFragmentDirections {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      class RegisterViewModel {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.dto {
        class RegistrationRequestDTO {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    class StartActivity {
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class User {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      interface UserDao {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.daos {
      class UserDao_Impl {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.dto {
        class UserDto {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class UserEvent {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.entities {
      class UserGroup {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.infrastructure.repositories {
      class UserRepository {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.login {
      package com.avansprojects.antl.ui.login.services {
        interface UserService {
        }
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.listeners {
      interface ViewModelListener {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.profile {
      class profileFragment {
      }
    }
  }
  

  package com.avansprojects.antl {
    package com.avansprojects.antl.ui.profile {
      class profileFragmentDirections {
      }
    }
  }
  

  AntlApp -up-|> Application
  AntlDatabase -up-|> RoomDatabase
  AntlDatabase_Impl -up-|> AntlDatabase
  AntlDatabase_Impl o-- UserDao : _userDao
  AntlDatabase_Impl o-- EventDao : _eventDao
  AntlDatabase_Impl o-- FriendDao : _friendDao
  AntlDatabase_Impl o-- EventDateDao : _eventDateDao
  BottomOffsetDecoration -up-|> ItemDecoration
  ContactRepository o-- FriendDao : mContacts
  CreateEventDateFragment -up-|> DatePickerListener
  CreateEventDateFragment -up-|> ViewModelListener
  CreateEventDateFragment -up-|> Fragment
  CreateEventDateFragment o-- EventDateAdapter : mAdapter
  CreateEventDateFragment o-- CreateEventViewModel : mViewModel
  CreateEventDescriptionFragment -up-|> Fragment
  CreateEventFragment -up-|> Fragment
  CreateEventFragment o-- CreateEventViewModel : mViewModel
  CreateEventFragmentDirections -up-|> NavGraphDirections
  CreateEventImageFragment -up-|> Fragment
  CreateEventImageFragment o-- CreateEventViewModel : mViewModel
  CreateEventNameFragment -up-|> Fragment
  CreateEventNameFragment o-- CreateEventViewModel : mViewModel
  CreateEventViewModel -up-|> AsyncTaskListener
  CreateEventViewModel -up-|> AndroidViewModel
  CreateEventViewModel o-- EventRepository : mEventRepository
  CreateEventViewModel o-- EventDateRepository : mEventDateRepository
  DataBinderMapperImpl -up-|> MergedDataBinderMapper
  DataBinderMapperImpl -up-|> DataBinderMapper
  DatePickerFactory o-- DatePickerListener : mListener
  Event -up-|> Comparable
  EventDao_Impl -up-|> EventDao
  EventDate -up-|> Comparable
  EventDateAdapter -up-|> Adapter
  EventDateAdapter o-- ViewModelListener : mListener
  EventDateDao_Impl -up-|> EventDateDao
  EventDateRepository o-- EventDateDao : mEventDateDao
  EventOverviewAdapter -up-|> Adapter
  EventOverviewFragment -up-|> Fragment
  EventOverviewFragment o-- EventOverviewViewModel : _ViewModel
  EventOverviewFragmentDirections -up-|> NavGraphDirections
  EventOverviewViewModel -up-|> AndroidViewModel
  EventOverviewViewModel o-- EventRepository : _EventRepository
  EventRepository o-- EventDao : mEventDao
  FriendAddFragment -up-|> Fragment
  FriendAddFragment o-- FriendAddViewModel : mViewModel
  FriendAddFragmentDirections -up-|> NavGraphDirections
  FriendAddViewModel -up-|> AndroidViewModel
  FriendCardViewHolder -up-|> ViewHolder
  FriendCardViewHolder o-- FriendAddViewModel : mViewModel
  FriendDao_Impl -up-|> FriendDao
  FriendOverviewAdapter -up-|> Adapter
  FriendOverviewAdapter o-- FriendCardViewHolder : mCardViewHolder
  FriendOverviewFragment -up-|> Fragment
  FriendOverviewFragment o-- FriendOverviewViewModel : mViewModel
  FriendOverviewFragment o-- FriendOverviewAdapter : mAdapter
  FriendOverviewFragmentDirections -up-|> NavGraphDirections
  FriendOverviewViewModel -up-|> AndroidViewModel
  FriendOverviewViewModel o-- ContactRepository : mContactRepository
  GeneratedAppGlideModuleImpl -up-|> GeneratedAppGlideModule
  GeneratedAppGlideModuleImpl o-- MyAppGlideModule : appGlideModule
  GeneratedRequestManagerFactory -up-|> RequestManagerFactory
  GlideOptions -up-|> Cloneable
  GlideOptions -up-|> RequestOptions
  GlideRequest -up-|> Cloneable
  GlideRequest -up-|> RequestBuilder
  GlideRequests -up-|> RequestManager
  LoginFragment -up-|> Fragment
  LoginFragment o-- LoginViewModel : mViewModel
  LoginFragmentDirections -up-|> NavGraphDirections
  LoginViewModel -up-|> ViewModel
  MyAppGlideModule -up-|> AppGlideModule
  NonSwipeableViewPager -up-|> ViewPager
  ProfileViewModel -up-|> AndroidViewModel
  ProfileViewModel o-- UserRepository : userRepository
  ProfileViewModel o-- User : mainUser
  RegisterFragment -up-|> Fragment
  RegisterFragment o-- RegisterViewModel : mViewModel
  RegisterFragmentDirections -up-|> NavGraphDirections
  RegisterViewModel -up-|> ViewModel
  StartActivity -up-|> AppCompatActivity
  UserDao_Impl -up-|> UserDao
  UserEvent o-- Availability : availability
  UserRepository o-- UserDao : mUserDao
  profileFragment -up-|> Fragment
  profileFragment o-- ProfileViewModel : mViewModel
  profileFragmentDirections -up-|> NavGraphDirections


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
